---
# This ZTP has dependency on a management cluster
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"

resources:
  #- 00-namespace.yaml
  #- 01-pullsecret.yaml
  - 02-aci.yaml
  - 03-clusterdeployment.yaml
  - 04-klusterletaddon.yaml
  - 05-managedcluster.yaml
  - 06-infraenv-volante-cars-lab.yaml
  - 07-nmstate-volante-cars-lab.yaml
  - 08-bmh-volante-cars-lab-cplane.yaml
