---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  #####################################################
  # Operators for MGMT Clusters
  #####################################################
  # Common Telco Optimizations
  - github.com/openshift-telco/telco-gitops/base/configs/telco-optimized?ref=main
  # OpenShift Local Storage
  - github.com/openshift-telco/telco-gitops/base/operators/local-storage-operator?ref=main
  # OpenShift GitOps
  - github.com/redhat-cop/gitops-catalog/openshift-gitops-operator/overlays/stable?ref=main
  # OpenShift Pipelines
  - github.com/redhat-cop/gitops-catalog/openshift-pipelines-operator/overlays/stable?ref=main
  # OpenShift Serverless
  #- github.com/openshift-telco/telco-gitops/base/operators/openshift-serverless
  # Red Hat Advanced Cluster Manager for Kubernetes
  - github.com/redhat-cop/gitops-catalog/advanced-cluster-management/operator/overlays/release-2.5?ref=main
  - github.com/redhat-cop/gitops-catalog/advanced-cluster-management/instance/base?ref=main
  # OpenShift Data Fabric
  # - github.com/openshift-telco/telco-gitops/base/operators/openshift-container-storage
  # Quay Enterprise
  # - github.com/openshift-telco/telco-gitops/base/operators/quay-enterprise-operator
  # OpenShift Logging
  # - github.com/openshift-telco/telco-gitops/base/operators/openshift-logging
resources:
  - https://raw.githubusercontent.com/openshift-telco/telco-gitops/main/base/operators/local-storage-operator/02-lso-auto-discovery-devices-EXAMPLE.yaml
