---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super1-jimmy-cars-lab
  namespace: jimmy-cars-lab
  labels:
    cluster-name: jimmy-nmstate
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        ipv4:
          address:
          - ip: 10.50.58.121
            prefix-length: 24
          enabled: true
        ipv6:
          enabled: true
          address:
          - ip: fd00:6:6:2058::121
            prefix-length: 64
          autoconf: false
          dhcp: false
    dns-resolver:
      config:
        server:
        - 10.40.0.100
        - fd00:6:6:11::52
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.50.58.1
          next-hop-interface: enp1s0
        - destination: ::/0
          next-hop-address: fd00:6:6:2058::1
          next-hop-interface: enp1s0
  interfaces:
    - name: enp1s0
      macAddress: DE:AD:BE:EF:B0:1D
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super2-jimmy-cars-lab
  namespace: jimmy-cars-lab
  labels:
    cluster-name: jimmy-nmstate
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        ipv4:
          address:
          - ip: 10.50.58.122
            prefix-length: 24
          enabled: true
        ipv6:
          enabled: true
          address:
          - ip: fd00:6:6:2058::122
            prefix-length: 64
          autoconf: false
          dhcp: false
    dns-resolver:
      config:
        server:
        - 10.40.0.100
        - fd00:6:6:11::52
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.50.58.1
          next-hop-interface: enp1s0
        - destination: ::/0
          next-hop-address: fd00:6:6:2058::1
          next-hop-interface: enp1s0
  interfaces:
    - name: enp1s0
      macAddress: DE:AD:BE:EF:0D:47
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super3-jimmy-cars-lab
  namespace: jimmy-cars-lab
  labels:
    cluster-name: jimmy-nmstate
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        ipv4:
          address:
          - ip: 10.50.58.123
            prefix-length: 24
          enabled: true
        ipv6:
          enabled: true
          address:
          - ip: fd00:6:6:2058::123
            prefix-length: 64
          autoconf: false
          dhcp: false
    dns-resolver:
      config:
        server:
        - 10.40.0.100
        - fd00:6:6:11::52
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.50.58.1
          next-hop-interface: enp1s0
        - destination: ::/0
          next-hop-address: fd00:6:6:2058::1
          next-hop-interface: enp1s0
  interfaces:
    - name: enp1s0
      macAddress: DE:AD:BE:EF:D8:86
