---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-super1-jimmy-cars-lab
  namespace: jimmy-cars-lab
data:
  username: cm9vdA==
  password: YWx0aW9zdGFyMTIz
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-super2-jimmy-cars-lab
  namespace: jimmy-cars-lab
data:
  username: cm9vdA==
  password: YWx0aW9zdGFyMTIz
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-super3-jimmy-cars-lab
  namespace: jimmy-cars-lab
data:
  username: cm9vdA==
  password: YWx0aW9zdGFyMTIz
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: super1-jimmy-cars-lab
  namespace: jimmy-cars-lab
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-jimmy-cars-lab"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "super1"
    bmac.agent-install.openshift.io/role: master
    bmac.agent-install.openshift.io/installer-args: '["--copy-network"]'
spec:
  online: true
  bootMACAddress: DE:AD:BE:EF:B0:1D
  automatedCleaningMode: disabled
  bmc:
    address: redfish-virtualmedia+https://kvmhost3.caravan.cars.lab:8082/redfish/v1/Systems/d1e8207c-bb4f-11ec-8422-0242ac120002
    credentialsName: bmc-super1-jimmy-cars-lab
    disableCertificateVerification: True
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: super2-jimmy-cars-lab
  namespace: jimmy-cars-lab
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-jimmy-cars-lab"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "super2"
    bmac.agent-install.openshift.io/role: master
    bmac.agent-install.openshift.io/installer-args: '["--copy-network"]'
spec:
  online: true
  bootMACAddress: DE:AD:BE:EF:0D:47
  automatedCleaningMode: disabled
  bmc:
    address: redfish-virtualmedia+https://kvmhost3.caravan.cars.lab:8082/redfish/v1/Systems/dda6ac44-bb4f-11ec-8422-0242ac120002
    credentialsName: bmc-super2-jimmy-cars-lab
    disableCertificateVerification: True
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: super3-jimmy-cars-lab
  namespace: jimmy-cars-lab
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-jimmy-cars-lab"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "super3"
    bmac.agent-install.openshift.io/role: master
    bmac.agent-install.openshift.io/installer-args: '["--copy-network"]'
spec:
  online: true
  bootMACAddress: DE:AD:BE:EF:D8:86
  automatedCleaningMode: disabled
  bmc:
    address: redfish-virtualmedia+https://kvmhost3.caravan.cars.lab:8082/redfish/v1/Systems/e216429e-bb4f-11ec-8422-0242ac120002
    credentialsName: bmc-super3-jimmy-cars-lab
    disableCertificateVerification: True
