#oc create secret generic assisted-deployment-pull-secret -n skylark-cars-lab --from-file=.dockerconfigjson=/home/user/pull-secret-fun/pull-secret-2.json --type=kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigson: FILL IN HERE
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: blazer-cars-lab
type: kubernetes.io/dockerconfigjson
