---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super1-caravan-cars-lab
  namespace: caravan-cars-lab
  labels:
    cluster-name: caravan-nmstate
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        ipv4:
          address:
          - ip: 10.70.100.92
            prefix-length: 24
          enabled: true
        ipv6:
          enabled: true
          address:
          - ip: fd00:6:6:2053::92
            prefix-length: 64
          autoconf: false
          dhcp: false
    dns-resolver:
      config:
        server:
        - 10.40.0.100
        - fd00:6:6:11::52
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.70.100.1
          next-hop-interface: enp1s0
        - destination: ::/0
          next-hop-address: fd00:6:6:2053::1
          next-hop-interface: enp1s0
  interfaces:
    - name: enp1s0
      macAddress: 52:12:6D:48:68:8B
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super2-caravan-cars-lab
  namespace: caravan-cars-lab
  labels:
    cluster-name: caravan-nmstate
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        ipv4:
          address:
          - ip: 10.70.100.93
            prefix-length: 24
          enabled: true
        ipv6:
          enabled: true
          address:
          - ip: fd00:6:6:2053::93
            prefix-length: 64
          autoconf: false
          dhcp: false
    dns-resolver:
      config:
        server:
        - 10.40.0.100
        - fd00:6:6:11::52
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.70.100.1
          next-hop-interface: enp1s0
        - destination: ::/0
          next-hop-address: fd00:6:6:2053::1
          next-hop-interface: enp1s0
  interfaces:
    - name: enp1s0
      macAddress: 52:12:6D:48:68:8C
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super3-caravan-cars-lab
  namespace: caravan-cars-lab
  labels:
    cluster-name: caravan-nmstate
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        ipv4:
          address:
          - ip: 10.70.100.94
            prefix-length: 24
          enabled: true
        ipv6:
          enabled: true
          address:
          - ip: fd00:6:6:2053::94
            prefix-length: 64
          autoconf: false
          dhcp: false
    dns-resolver:
      config:
        server:
        - 10.40.0.100
        - fd00:6:6:11::52
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.70.100.1
          next-hop-interface: enp1s0
        - destination: ::/0
          next-hop-address: fd00:6:6:2053::1
          next-hop-interface: enp1s0
  interfaces:
    - name: enp1s0
      macAddress: 52:12:6D:48:68:8D
