apiVersion: sts.silicom.com/v1alpha1
kind: StsConfig
metadata:
  name: gm-1
  namespace: openshift-operators
spec:
  namespace: openshift-operators
  nodeSelector:
    sts.silicom.com/config: "gm-1"
  mode: T-GM.8275.1
  interfaces:
    - ethName: enp81s0f3
      synce: 1
      holdoff: 500
      mode: Master
      ethPort: 0

