---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-local-storage
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lso-filesystemclass
---
apiVersion: config.openshift.io/v1
kind: Scheduler
metadata:
  name: cluster
spec:
  mastersSchedulable: true
---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-disks
  namespace: openshift-local-storage
spec:
  managementState: Managed
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: ran.openshift.io/lso
        operator: Exists
  storageClassDevices:
  - devicePaths:
    - /dev/autopart/lv_1
    - /dev/autopart/lv_2
    - /dev/autopart/lv_3
    fsType: xfs
    storageClassName: lso-filesystemclass
    volumeMode: Filesystem
  - devicePaths:
    - /dev/autopart/lv_4
    - /dev/autopart/lv_5
    storageClassName: lso-blockclass
    volumeMode: Block
---
apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeDiscovery
metadata:
  name: auto-discover-devices
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: ran.openshift.io/lso
        operator: Exists
---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/master: ""
  replicas: 3
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-local-storage
  namespace: openshift-local-storage
spec:
  targetNamespaces:
  - openshift-local-storage
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-local-storage-operator
  namespace: openshift-local-storage
spec:
  channel: "4.9"
  installPlanApproval: Automatic
  name: local-storage-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
