apiVersion: v1
kind: ConfigMap
metadata:
  name: disconnected-mirror-config
  namespace: open-cluster-management
  labels:
    app: assisted-service
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIF2zCCA8OgAwIBAgIUVGQ72dVHpnSbSGCTejpUiXEr15swDQYJKoZIhvcNAQEL
    BQAwbjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk5DMRAwDgYDVQQHDAdSYWxlaWdo
    MRYwFAYDVQQKDA1SZWQgSGF0LCBJbmMuMQwwCgYDVQQLDANMYWIxGjAYBgNVBAMM
    EXJlZ2lzdHJ5LmNhcnMubGFiMB4XDTIyMDEzMTE0NDIxM1oXDTMyMDEyOTE0NDIx
    M1owbjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk5DMRAwDgYDVQQHDAdSYWxlaWdo
    MRYwFAYDVQQKDA1SZWQgSGF0LCBJbmMuMQwwCgYDVQQLDANMYWIxGjAYBgNVBAMM
    EXJlZ2lzdHJ5LmNhcnMubGFiMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
    AgEAqbg2FA/R8+mP1fy+CDdeJocYiJc2VWdEka4VyxGnHJRiGOOLGD2xJ/93/Phh
    qsevyo4trFAl9U7SVdB8AdpFm8OhGBbYsm0TLFQ5c6GBiZNjG+xUbSN3xqKnfYtY
    LOwMQ2KvDRtbCIBR+Vue7DgeTzfW7bWYsUpSJQOBD+911gaLdpM7vHT+mttqXXh6
    yY5TZ+RVYjnA7DnBPf3xVJWu6t4uMDYwhUGlyJmGnGZt4HjWURUbYEIXUpLuzVOX
    nREjg/AO8dNdAGBS7PA5BsiHdqDNtOymCdghgvRvZagn4pIg28ZOmZvejEMghGAF
    kPq7oRnI4pOnH6XqoIO3guj2vwAyN9EhJlao6O16dmbO0Gj9Am3ELC032RCviI0X
    7ZaBBimFbUw0LvHyb/wLiGMk2EULFsWPnD6qswBysqf4Vnxyu//MhizN5i7v6QXG
    cZcdn2dKVibqF2BV5Bi/IVuGQz6vGJMqdA5AxoOMPkiVUHPsBIybw1zTAQUlgac1
    1dGmpDbol0ZdMmV+rLUJJLsGEXLd0xZIZWKkF7fY3+j3bLfUSsMcGCtDeVjxYFGi
    EGk36cHJWfzmllD5UTXkMpSRfEE6HnNlW62U1O8lZn1OCd9LXXUoPINlfMlGn6p7
    700tfHYtsMYiX83GDM0noQYB7xjpyWEZA9rkQSVL2XZqP88CAwEAAaNxMG8wHAYD
    VR0RBBUwE4IRcmVnaXN0cnkuY2Fycy5sYWIwDwYDVR0TAQH/BAUwAwEB/zAdBgNV
    HQ4EFgQUD5MYNNZg17WLbaXcdpNUUWS2QcwwHwYDVR0jBBgwFoAUD5MYNNZg17WL
    baXcdpNUUWS2QcwwDQYJKoZIhvcNAQELBQADggIBAG47edy+zodNQe4+k3bFB/Ls
    W7B2/dMwk+dl8aA5iLVWQQbSE643z39+hm7AR1prnHrtN51KdpV0TaRMbwDS97g8
    JLDzehuBvyBFTzvKw/RrQvevdCLWKmNV2wLiYF6wJgG5P3ke6ujsMu7m+oh3XcZi
    9FW6k3RL45r2rW0PWbf6jJBHFR4QdYpH97YRKgm1AXbldl2OZrwUA1sTEJi6CcSZ
    IDz9ZitUfNMSBWoDqTk0Ma1qEHZqfJYcKfwyWg8Ve8hSppxl8waoT8O52e3Q4s/Q
    FM352huhUHefs+t6BwoLISSTLmrRpGLeoUOzZp5ihK0R0iCuF2qZQNM6uvcYnlvP
    cFpb5ieIui1KTKQM5xURs9eNKr6HJiHrnqcv3oa7nlFosLNM9gamazK086+TOY+M
    X8TDCA1BIQQtYYhAw7ZEDxJO1OKhidbXNxgz08F8GiIQxpbzfosImcf/QqkQ0IUW
    z7ZcQ/fC1FbUUz5JVqZM6uTaK4mIcWXQ/H9YKONku3RTNLW1wxtWg1rRRA3zCvBb
    AjVFoDQLVnN1lmq9jkRsnrza8sV+KslaY1eCcy2jVD1i7c6fC1HRaaRdR6hUqVjg
    mX+QT6dj2XmC228Njb+lZILFWptOY42yed2VdceH28zS2Lv2CMbFOxRuemEynitI
    UFehtui/cv4riy/ABiPS
    -----END CERTIFICATE-----
  registries.conf: |
    unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]

    [[registry]]
      prefix = ""
      location = "registry.redhat.io/rhacm2"
      mirror-by-digest-only = true

      [[registry.mirror]]
        location = "registry.cars.lab:5000/rhacm2"

    [[registry]]
      prefix = ""
      location = "registry.redhat.io/openshift4"
      mirror-by-digest-only = true

      [[registry.mirror]]
        location = "registry.cars.lab:5000/ocp4/openshift4"

    [[registry]]
      prefix = ""
      location = "registry.redhat.io/redhat"
      mirror-by-digest-only = true

      [[registry.mirror]]
        location = "registry.cars.lab:5000/redhat"

    [[registry]]
      prefix = ""
      location = "registry.redhat.io/rhel8"
      mirror-by-digest-only = true

      [[registry.mirror]]
        location = "registry.cars.lab:5000/rhel8"

    [[registry]]
      prefix = ""
      location = "quay.io/operator-framework"
      mirror-by-digest-only = true

      [[registry.mirror]]
        location = "registry.cars.lab:5000/operator-framework"
