---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: openshift-v4.8.29
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.8.29-x86_64
---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: openshift-v4.9.22
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.9.22-x86_64
---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: openshift-4.10.1
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.10.1-x86_64
