---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: skylark-cars-lab
  namespace: skylark-cars-lab
spec:
  baseDomain: cars.lab
  clusterName: skylark
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: skylark-cars-lab
    version: v1beta1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: skylark-cars-lab
  pullSecretRef:
    name: assisted-deployment-pull-secret
